// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCVnGLDqEIPHfTO7XAghRviVAkF8VXNJI',
    appId: '1:424691128075:web:de45f7bdd51ba27f18b40e',
    messagingSenderId: '424691128075',
    projectId: 'sarowar-5c1c5',
    authDomain: 'sarowar-5c1c5.firebaseapp.com',
    storageBucket: 'sarowar-5c1c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6_jrRKlD2iGMYmy6gjHM8up6yneA4aj0',
    appId: '1:424691128075:android:bc891ae5f979060b18b40e',
    messagingSenderId: '424691128075',
    projectId: 'sarowar-5c1c5',
    storageBucket: 'sarowar-5c1c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR0rFmEXkTiSaYNBPtoTrQL4CTYsfBpfA',
    appId: '1:424691128075:ios:21a68354f43898de18b40e',
    messagingSenderId: '424691128075',
    projectId: 'sarowar-5c1c5',
    storageBucket: 'sarowar-5c1c5.appspot.com',
    iosClientId: '424691128075-1a4hgaugc6o8n85v393cq88m8muel70s.apps.googleusercontent.com',
    iosBundleId: 'com.example.sarowar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR0rFmEXkTiSaYNBPtoTrQL4CTYsfBpfA',
    appId: '1:424691128075:ios:21a68354f43898de18b40e',
    messagingSenderId: '424691128075',
    projectId: 'sarowar-5c1c5',
    storageBucket: 'sarowar-5c1c5.appspot.com',
    iosClientId: '424691128075-1a4hgaugc6o8n85v393cq88m8muel70s.apps.googleusercontent.com',
    iosBundleId: 'com.example.sarowar',
  );
}
